spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  sql:
    init:
      mode: always

  jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

      properties:
        hibernate:
          format_sql: true

      show-sql: true

      defer-datasource-initialization: true