spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: library
      port: 27017

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local