spring:
  data:
    mongodb:
      database: library
      port: 27017

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local